# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
color: '#fab005'
exclude:
  [
    CNAME,
    README.md,
    NOTES.md,
    LICENSE.md,
    .gitignore,
    package.json,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
  ]
permalink: /:title/
compress_html:
  clippings: all
  comments: all
dark_theme: false

# Site meta
title: Yong's life log
tagline: 'films & other stuff'
description: 'null'
keywords: 'connor, b√§r, designer, traveller, code, jekyll, developer, theme'
url: https://yonglhuang.com
baseurl: /lifelog
assets: /assets
images: /images/
image: cover-large.png
logo: /assets/icons/logo.png

author:
  name: Yong Huang
  bio: Hi, I'm Yong, the author of this blog. Nice to meet you!
  
  url: https://yonglhuang.com
  email: yh849@cornell.edu
  twitter: 

social:
  twitter: https://twitter.com/
  instagram: https://instagram.com/
  github: https://github.com/

version: 2.0.0

github:
  repo: https://github.com/

# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass: 400, 600, 800

# google_analytics_key: UA-37412525-4
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
  

collections:
  recipes:
    output: true

defaults:
  - scope:
      path: '' 
      type: posts
    values:
      layout: post
      lang: en
      permalink: /news/:title/
  - scope:
      path: ''
      type: recipes
    values:
      layout: recipe
      lang: en
      permalink: /:title/
